### ISSUE TITLE
In-app purchasing by cryptocurrency

### ISSUE THREAD

**Issue by bdshahab** [defold/asset-portal#174]
<img width="290" alt="A" src="https://github.com/defold/asset-portal/assets/17976016/4248c736-8b83-4f12-ae16-61197dd3dc07">

<img width="290" alt="B" src="https://github.com/defold/asset-portal/assets/17976016/9bc13d39-5c83-4ca8-ad9f-9f594ab0f4fd">

{
    "name": "In-app purchasing by cryptocurrency",
    "description": "In-app purchasing (IAP) by cryptocurrency\nA simple way to enable in-app purchases using cryptocurrencies.\n\nA video clip about this method (A little different in appearance but the same in function):\n\nhttps://youtu.be/QOaZi6Bp4og\n",
    "license": "This is free and unencumbered software released into the public domain.",
    "author": "Shahab Baradaran Dilmaghani",
    "library_url": "",
    "project_url": "https://github.com/bdshahab/in-app-purchasing-by-crypto",
    "forum_url": "",
    "website_url": "",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux"
    ],
    "tags": [
        "monetization"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
Thank you for suggesting to add this to the asset portal. I would recommend that you rework this such that the actual code which you now have in .gui_script files is moved into Lua modules so the project becomes modular and easy to reuse in an existing project.

We could treat this project as an example project, but we prefer that assets in the portal are actually easy to use in existing projects.

* https://defold.com/manuals/libraries/
* https://defold.com/manuals/modules/

**Comment by bdshahab** [comment]
As I progress in learning Lua and Defold, I try to get closer to the standards and be able to modify the code accordingly.

**Comment by britzl** [comment]
I'm closing this for now. @bdshahab please reopen if you successfully rework this into a reusable Defold library project.

**Comment by bdshahab** [comment]
Sure! But I wish someone like you would cooperate and help me produce a reusable Defold library project.
