### ISSUE TITLE
Sprite Fusion - A Free, easy-to-use level editor

### ISSUE THREAD

**Issue by Hugo-Dz** [defold/asset-portal#180]
Optionally also attach two images Sprite Fusion-hero.[png|jpg] (max 2400x666) and Sprite Fusion-thumb.[png|jpg] (max 580x380).
{
    "name": "Sprite Fusion",
    "description": "A free, SUPER easy-to-use tilemap editor that exports maps to Defold Tilemap and Tilesource in one click.",
    "license": "N/A",
    "author": "Hugo",
    "library_url": "",
    "project_url": "https://www.spritefusion.com/",
    "forum_url": "",
    "website_url": "https://www.spritefusion.com/",
    "platforms": [
        "html5"
    ],
    "tags": [
        "art assets",
        "editor",
        "tools",
        "util"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
Thank you! Sprite Fusion looks great!

**Comment by Hugo-Dz** [comment]
Thank you! :D
