### ISSUE TITLE
LualocaDE

### ISSUE THREAD

**Issue by Mantyi-Studio** [defold/asset-portal#212]
Optionally also attach two images LualocaDE-hero.[png|jpg] (max 2400x666) and LualocaDE-thumb.[png|jpg] (max 580x380).
{
    "name": "LualocaDE",
    "description": "Localize your game/app on Defold using this autotranslator with convenient localization json files that supports entries",
    "license": "MIT",
    "author": "Mantyi Studio (Nava)",
    "library_url": "",
    "project_url": "https://github.com/Mantyi-Studio/lualocaDE",
    "forum_url": "https://forum.defold.com/t/lualocade-auto-text-localizer/77818",
    "website_url": "",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "gui"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
Added https://github.com/defold/asset-portal/commit/e06038595cab59129398a4bc0579959dbcb3d5d2
