### ISSUE TITLE
Defold Tiny ECS

### ISSUE THREAD

**Issue by ivanquirino** [defold/asset-portal#217]
Optionally also attach two images Defold Tiny ECS-hero.[png|jpg] (max 2400x666) and Defold Tiny ECS-thumb.[png|jpg] (max 580x380).
{
    "name": "Defold Tiny ECS",
    "description": "The Tiny ECS library packaged as a Defold library.",
    "license": "MIT",
    "author": "MegaCrab Games",
    "library_url": "https://github.com/ivanquirino/defold-tiny-ecs/archive/refs/tags/1.3-3.zip",
    "project_url": "https://github.com/ivanquirino/defold-tiny-ecs",
    "forum_url": "",
    "website_url": "",
    "platforms": [
        "android",
        "ios",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "lua",
        "system"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by britzl** [comment]
Thanks! Added https://github.com/defold/asset-portal/commit/2a3d9ba689115d7b5f00b35809f79c47d9ef5b04
