### ISSUE TITLE
Planetary Processing

### ISSUE THREAD

**Issue by Abrasam** [defold/asset-portal#219]
Optionally also attach two images Planetary Processing-hero.[png|jpg] (max 2400x666) and Planetary Processing-thumb.[png|jpg] (max 580x380).
{
    "name": "Planetary Processing",
    "description": "Planetary Processing is a low-cost, easy to use multiplayer game engine that integrates with Defold to make building any type of multiplayer game easy, from MMO to team shooters to party games!",
    "license": "MIT",
    "author": "Planetary Processing Ltd",
    "library_url": "",
    "project_url": "https://github.com/planetary-Processing/defold-sdk",
    "forum_url": "",
    "website_url": "https://planetaryprocessing.io",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "lua",
        "network",
        "platform",
        "system"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by Abrasam** [comment]
![Thumb](https://github.com/user-attachments/assets/657f6fba-8a2f-4e00-87f7-7d05bf968e57)
![Hero](https://github.com/user-attachments/assets/9e659bba-9ad2-44ed-abef-1996ac68941b)

**Comment by Abrasam** [comment]
@britzl thought I'd ping you 😅

**Comment by britzl** [comment]
> @britzl thought I'd ping you 😅

Thanks! Exciting!
