### ISSUE TITLE
UMP - Google User Messaging Platform (Android)

### ISSUE THREAD

**Issue by tocaRepo** [defold/asset-portal#224]
Optionally also attach two images UMP - Google User Messaging Platform (Android)-hero.[png|jpg] (max 2400x666) and UMP - Google User Messaging Platform (Android)-thumb.[png|jpg] (max 580x380).
{
    "name": "UMP - Google User Messaging Platform (Android)",
    "description": "This Defold extension allows you to integrate Google's User Messaging Platform (UMP) into your Defold game to manage user consent for ads on Android. It helps you request consent information, show the consent form, and check the user's consent status",
    "license": "MIT License",
    "author": "Toca (tc)",
    "library_url": "https://github.com/tocaRepo/defold-androidextension-ump/archive/refs/tags/v0.0.6.zip",
    "project_url": "https://github.com/tocaRepo/defold-androidextension-ump",
    "forum_url": "https://forum.defold.com/t/defold-google-user-messaging-platform-ump-extension/78722",
    "website_url": "",
    "platforms": [
        "android"
    ],
    "tags": [
        "ads",
        "monetization",
        "platform"
    ],
    "images": {
        "hero": "",
        "thumb": ""
    }
}

**Comment by tocaRepo** [comment]
580x380


![unnamed (1)](https://github.com/user-attachments/assets/1c297bc0-1d8e-4f48-a844-8fc344c3ae48)

**Comment by tocaRepo** [comment]
@britzl a ping just in case you guys are not monitoring issues.

Apologies if you do :D

**Comment by britzl** [comment]
Thanks. I've created https://github.com/defold/asset-portal/blob/master/assets/ump.json

Please submit changes to this entry as PRs

**Comment by tocaRepo** [comment]
Thank you @britzl ! 
PR created for the images:
https://github.com/defold/asset-portal/pull/226
