### ISSUE TITLE
Defold Wrap

### ISSUE THREAD

**Issue by baochungit** [defold/asset-portal#230]
Optionally also attach two images Defold Wrap-hero.[png|jpg] (max 2400x666) and Defold Wrap-thumb.[png|jpg] (max 580x380).
{
    "name": "Defold Wrap",
    "description": "This library aims to help you change the way you write code on Defold.",
    "license": "MIT",
    "author": "Chung Xa",
    "library_url": "https://github.com/baochungit/defold-wrap/archive/master.zip",
    "project_url": "https://github.com/baochungit/defold-wrap/",
    "forum_url": "",
    "website_url": "",
    "platforms": [
        "android",
        "ios",
        "macos",
        "windows",
        "linux",
        "html5"
    ],
    "tags": [
        "lua",
        "system",
        "gui",
        "util"
    ],
    "images": {
        "hero": "https://baochungit.github.io/public/images/defold-wrap-banner.jpg",
        "thumb": "https://baochungit.github.io/public/images/defold-wrap-logo.jpg"
    }
}

**Comment by britzl** [comment]
My apologies. I missed this asset. Do you still want to have it added to the Asset Portal?
